version: "3"
services:
    valheim:
        image: mbround18/valheim:latest
        ports:
            - 2456:2456/udp
            - 2457:2457/udp
            - 2458:2458/udp
        environment:
            - PORT=2456
            - NAME="jaguarao"
            - WORLD="Dedicated"
            - PASSWORD="bug123456"
            - TZ=America/Chicago
            - PUBLIC=1
            - AUTO_UPDATE=1
            - AUTO_UPDATE_SCHEDULE="0 1 * * *"
            - AUTO_BACKUP=1
            - AUTO_BACKUP_SCHEDULE="*/15 * * * *"
            - AUTO_BACKUP_REMOVE_OLD=1
            - AUTO_BACKUP_DAYS_TO_LIVE=3
            - AUTO_BACKUP_ON_UPDATE=1
            - AUTO_BACKUP_ON_SHUTDOWN=1
        volumes:
            - ./valheim/saves:/home/steam/.config/unity3d/IronGate/Valheim
            - ./valheim/server:/home/steam/valheim
            - ./valheim/backups:/home/steam/backups

    web:
        image: nginx
        volumes:
            - ./templates:/etc/nginx/templates
        ports:
            - "80:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80